// SPDX-License-Identifier: BSD-3-Clause
#pragma once
#include "libretro_vulkan.h"
#include <stdexcept>
#include <string>
// Resolved exclusively from the frontend; symbols are hidden by the core export list.
inline PFN_vkAllocateCommandBuffers vkAllocateCommandBuffers = nullptr;
inline PFN_vkAllocateDescriptorSets vkAllocateDescriptorSets = nullptr;
inline PFN_vkBeginCommandBuffer vkBeginCommandBuffer = nullptr;
inline PFN_vkCmdBeginRendering vkCmdBeginRendering = nullptr;
inline PFN_vkCmdBindDescriptorSets vkCmdBindDescriptorSets = nullptr;
inline PFN_vkCmdBindPipeline vkCmdBindPipeline = nullptr;
inline PFN_vkCmdBindVertexBuffers vkCmdBindVertexBuffers = nullptr;
inline PFN_vkCmdCopyBufferToImage vkCmdCopyBufferToImage = nullptr;
inline PFN_vkCmdDispatch vkCmdDispatch = nullptr;
inline PFN_vkCmdDraw vkCmdDraw = nullptr;
inline PFN_vkCmdEndRendering vkCmdEndRendering = nullptr;
inline PFN_vkCmdPipelineBarrier2 vkCmdPipelineBarrier2 = nullptr;
inline PFN_vkCmdPushConstants vkCmdPushConstants = nullptr;
inline PFN_vkCmdSetScissor vkCmdSetScissor = nullptr;
inline PFN_vkCmdSetViewport vkCmdSetViewport = nullptr;
inline PFN_vkCreateCommandPool vkCreateCommandPool = nullptr;
inline PFN_vkCreateComputePipelines vkCreateComputePipelines = nullptr;
inline PFN_vkCreateDescriptorPool vkCreateDescriptorPool = nullptr;
inline PFN_vkCreateDescriptorSetLayout vkCreateDescriptorSetLayout = nullptr;
inline PFN_vkCreateFence vkCreateFence = nullptr;
inline PFN_vkCreateGraphicsPipelines vkCreateGraphicsPipelines = nullptr;
inline PFN_vkCreateImageView vkCreateImageView = nullptr;
inline PFN_vkCreatePipelineLayout vkCreatePipelineLayout = nullptr;
inline PFN_vkCreateSampler vkCreateSampler = nullptr;
inline PFN_vkCreateShaderModule vkCreateShaderModule = nullptr;
inline PFN_vkDestroyCommandPool vkDestroyCommandPool = nullptr;
inline PFN_vkDestroyDescriptorPool vkDestroyDescriptorPool = nullptr;
inline PFN_vkDestroyDescriptorSetLayout vkDestroyDescriptorSetLayout = nullptr;
inline PFN_vkDestroyFence vkDestroyFence = nullptr;
inline PFN_vkDestroyImageView vkDestroyImageView = nullptr;
inline PFN_vkDestroyPipeline vkDestroyPipeline = nullptr;
inline PFN_vkDestroyPipelineLayout vkDestroyPipelineLayout = nullptr;
inline PFN_vkDestroySampler vkDestroySampler = nullptr;
inline PFN_vkDestroyShaderModule vkDestroyShaderModule = nullptr;
inline PFN_vkDeviceWaitIdle vkDeviceWaitIdle = nullptr;
inline PFN_vkEndCommandBuffer vkEndCommandBuffer = nullptr;
inline PFN_vkGetPhysicalDeviceFormatProperties vkGetPhysicalDeviceFormatProperties = nullptr;
inline PFN_vkGetPhysicalDeviceProperties vkGetPhysicalDeviceProperties = nullptr;
inline PFN_vkQueueSubmit vkQueueSubmit = nullptr;
inline PFN_vkResetCommandBuffer vkResetCommandBuffer = nullptr;
inline PFN_vkResetFences vkResetFences = nullptr;
inline PFN_vkUpdateDescriptorSets vkUpdateDescriptorSets = nullptr;
inline PFN_vkWaitForFences vkWaitForFences = nullptr;
inline void load_vk_dispatch(const retro_hw_render_interface_vulkan& vk) {
    vkAllocateCommandBuffers = reinterpret_cast<PFN_vkAllocateCommandBuffers>(vk.get_device_proc_addr(vk.device, "vkAllocateCommandBuffers"));
    if (!vkAllocateCommandBuffers) throw std::runtime_error("Missing frontend Vulkan function: vkAllocateCommandBuffers");
    vkAllocateDescriptorSets = reinterpret_cast<PFN_vkAllocateDescriptorSets>(vk.get_device_proc_addr(vk.device, "vkAllocateDescriptorSets"));
    if (!vkAllocateDescriptorSets) throw std::runtime_error("Missing frontend Vulkan function: vkAllocateDescriptorSets");
    vkBeginCommandBuffer = reinterpret_cast<PFN_vkBeginCommandBuffer>(vk.get_device_proc_addr(vk.device, "vkBeginCommandBuffer"));
    if (!vkBeginCommandBuffer) throw std::runtime_error("Missing frontend Vulkan function: vkBeginCommandBuffer");
    vkCmdBeginRendering = reinterpret_cast<PFN_vkCmdBeginRendering>(vk.get_device_proc_addr(vk.device, "vkCmdBeginRendering"));
    if (!vkCmdBeginRendering) throw std::runtime_error("Missing frontend Vulkan function: vkCmdBeginRendering");
    vkCmdBindDescriptorSets = reinterpret_cast<PFN_vkCmdBindDescriptorSets>(vk.get_device_proc_addr(vk.device, "vkCmdBindDescriptorSets"));
    if (!vkCmdBindDescriptorSets) throw std::runtime_error("Missing frontend Vulkan function: vkCmdBindDescriptorSets");
    vkCmdBindPipeline = reinterpret_cast<PFN_vkCmdBindPipeline>(vk.get_device_proc_addr(vk.device, "vkCmdBindPipeline"));
    if (!vkCmdBindPipeline) throw std::runtime_error("Missing frontend Vulkan function: vkCmdBindPipeline");
    vkCmdBindVertexBuffers = reinterpret_cast<PFN_vkCmdBindVertexBuffers>(vk.get_device_proc_addr(vk.device, "vkCmdBindVertexBuffers"));
    if (!vkCmdBindVertexBuffers) throw std::runtime_error("Missing frontend Vulkan function: vkCmdBindVertexBuffers");
    vkCmdCopyBufferToImage = reinterpret_cast<PFN_vkCmdCopyBufferToImage>(vk.get_device_proc_addr(vk.device, "vkCmdCopyBufferToImage"));
    if (!vkCmdCopyBufferToImage) throw std::runtime_error("Missing frontend Vulkan function: vkCmdCopyBufferToImage");
    vkCmdDispatch = reinterpret_cast<PFN_vkCmdDispatch>(vk.get_device_proc_addr(vk.device, "vkCmdDispatch"));
    if (!vkCmdDispatch) throw std::runtime_error("Missing frontend Vulkan function: vkCmdDispatch");
    vkCmdDraw = reinterpret_cast<PFN_vkCmdDraw>(vk.get_device_proc_addr(vk.device, "vkCmdDraw"));
    if (!vkCmdDraw) throw std::runtime_error("Missing frontend Vulkan function: vkCmdDraw");
    vkCmdEndRendering = reinterpret_cast<PFN_vkCmdEndRendering>(vk.get_device_proc_addr(vk.device, "vkCmdEndRendering"));
    if (!vkCmdEndRendering) throw std::runtime_error("Missing frontend Vulkan function: vkCmdEndRendering");
    vkCmdPipelineBarrier2 = reinterpret_cast<PFN_vkCmdPipelineBarrier2>(vk.get_device_proc_addr(vk.device, "vkCmdPipelineBarrier2"));
    if (!vkCmdPipelineBarrier2) throw std::runtime_error("Missing frontend Vulkan function: vkCmdPipelineBarrier2");
    vkCmdPushConstants = reinterpret_cast<PFN_vkCmdPushConstants>(vk.get_device_proc_addr(vk.device, "vkCmdPushConstants"));
    if (!vkCmdPushConstants) throw std::runtime_error("Missing frontend Vulkan function: vkCmdPushConstants");
    vkCmdSetScissor = reinterpret_cast<PFN_vkCmdSetScissor>(vk.get_device_proc_addr(vk.device, "vkCmdSetScissor"));
    if (!vkCmdSetScissor) throw std::runtime_error("Missing frontend Vulkan function: vkCmdSetScissor");
    vkCmdSetViewport = reinterpret_cast<PFN_vkCmdSetViewport>(vk.get_device_proc_addr(vk.device, "vkCmdSetViewport"));
    if (!vkCmdSetViewport) throw std::runtime_error("Missing frontend Vulkan function: vkCmdSetViewport");
    vkCreateCommandPool = reinterpret_cast<PFN_vkCreateCommandPool>(vk.get_device_proc_addr(vk.device, "vkCreateCommandPool"));
    if (!vkCreateCommandPool) throw std::runtime_error("Missing frontend Vulkan function: vkCreateCommandPool");
    vkCreateComputePipelines = reinterpret_cast<PFN_vkCreateComputePipelines>(vk.get_device_proc_addr(vk.device, "vkCreateComputePipelines"));
    if (!vkCreateComputePipelines) throw std::runtime_error("Missing frontend Vulkan function: vkCreateComputePipelines");
    vkCreateDescriptorPool = reinterpret_cast<PFN_vkCreateDescriptorPool>(vk.get_device_proc_addr(vk.device, "vkCreateDescriptorPool"));
    if (!vkCreateDescriptorPool) throw std::runtime_error("Missing frontend Vulkan function: vkCreateDescriptorPool");
    vkCreateDescriptorSetLayout = reinterpret_cast<PFN_vkCreateDescriptorSetLayout>(vk.get_device_proc_addr(vk.device, "vkCreateDescriptorSetLayout"));
    if (!vkCreateDescriptorSetLayout) throw std::runtime_error("Missing frontend Vulkan function: vkCreateDescriptorSetLayout");
    vkCreateFence = reinterpret_cast<PFN_vkCreateFence>(vk.get_device_proc_addr(vk.device, "vkCreateFence"));
    if (!vkCreateFence) throw std::runtime_error("Missing frontend Vulkan function: vkCreateFence");
    vkCreateGraphicsPipelines = reinterpret_cast<PFN_vkCreateGraphicsPipelines>(vk.get_device_proc_addr(vk.device, "vkCreateGraphicsPipelines"));
    if (!vkCreateGraphicsPipelines) throw std::runtime_error("Missing frontend Vulkan function: vkCreateGraphicsPipelines");
    vkCreateImageView = reinterpret_cast<PFN_vkCreateImageView>(vk.get_device_proc_addr(vk.device, "vkCreateImageView"));
    if (!vkCreateImageView) throw std::runtime_error("Missing frontend Vulkan function: vkCreateImageView");
    vkCreatePipelineLayout = reinterpret_cast<PFN_vkCreatePipelineLayout>(vk.get_device_proc_addr(vk.device, "vkCreatePipelineLayout"));
    if (!vkCreatePipelineLayout) throw std::runtime_error("Missing frontend Vulkan function: vkCreatePipelineLayout");
    vkCreateSampler = reinterpret_cast<PFN_vkCreateSampler>(vk.get_device_proc_addr(vk.device, "vkCreateSampler"));
    if (!vkCreateSampler) throw std::runtime_error("Missing frontend Vulkan function: vkCreateSampler");
    vkCreateShaderModule = reinterpret_cast<PFN_vkCreateShaderModule>(vk.get_device_proc_addr(vk.device, "vkCreateShaderModule"));
    if (!vkCreateShaderModule) throw std::runtime_error("Missing frontend Vulkan function: vkCreateShaderModule");
    vkDestroyCommandPool = reinterpret_cast<PFN_vkDestroyCommandPool>(vk.get_device_proc_addr(vk.device, "vkDestroyCommandPool"));
    if (!vkDestroyCommandPool) throw std::runtime_error("Missing frontend Vulkan function: vkDestroyCommandPool");
    vkDestroyDescriptorPool = reinterpret_cast<PFN_vkDestroyDescriptorPool>(vk.get_device_proc_addr(vk.device, "vkDestroyDescriptorPool"));
    if (!vkDestroyDescriptorPool) throw std::runtime_error("Missing frontend Vulkan function: vkDestroyDescriptorPool");
    vkDestroyDescriptorSetLayout = reinterpret_cast<PFN_vkDestroyDescriptorSetLayout>(vk.get_device_proc_addr(vk.device, "vkDestroyDescriptorSetLayout"));
    if (!vkDestroyDescriptorSetLayout) throw std::runtime_error("Missing frontend Vulkan function: vkDestroyDescriptorSetLayout");
    vkDestroyFence = reinterpret_cast<PFN_vkDestroyFence>(vk.get_device_proc_addr(vk.device, "vkDestroyFence"));
    if (!vkDestroyFence) throw std::runtime_error("Missing frontend Vulkan function: vkDestroyFence");
    vkDestroyImageView = reinterpret_cast<PFN_vkDestroyImageView>(vk.get_device_proc_addr(vk.device, "vkDestroyImageView"));
    if (!vkDestroyImageView) throw std::runtime_error("Missing frontend Vulkan function: vkDestroyImageView");
    vkDestroyPipeline = reinterpret_cast<PFN_vkDestroyPipeline>(vk.get_device_proc_addr(vk.device, "vkDestroyPipeline"));
    if (!vkDestroyPipeline) throw std::runtime_error("Missing frontend Vulkan function: vkDestroyPipeline");
    vkDestroyPipelineLayout = reinterpret_cast<PFN_vkDestroyPipelineLayout>(vk.get_device_proc_addr(vk.device, "vkDestroyPipelineLayout"));
    if (!vkDestroyPipelineLayout) throw std::runtime_error("Missing frontend Vulkan function: vkDestroyPipelineLayout");
    vkDestroySampler = reinterpret_cast<PFN_vkDestroySampler>(vk.get_device_proc_addr(vk.device, "vkDestroySampler"));
    if (!vkDestroySampler) throw std::runtime_error("Missing frontend Vulkan function: vkDestroySampler");
    vkDestroyShaderModule = reinterpret_cast<PFN_vkDestroyShaderModule>(vk.get_device_proc_addr(vk.device, "vkDestroyShaderModule"));
    if (!vkDestroyShaderModule) throw std::runtime_error("Missing frontend Vulkan function: vkDestroyShaderModule");
    vkDeviceWaitIdle = reinterpret_cast<PFN_vkDeviceWaitIdle>(vk.get_device_proc_addr(vk.device, "vkDeviceWaitIdle"));
    if (!vkDeviceWaitIdle) throw std::runtime_error("Missing frontend Vulkan function: vkDeviceWaitIdle");
    vkEndCommandBuffer = reinterpret_cast<PFN_vkEndCommandBuffer>(vk.get_device_proc_addr(vk.device, "vkEndCommandBuffer"));
    if (!vkEndCommandBuffer) throw std::runtime_error("Missing frontend Vulkan function: vkEndCommandBuffer");
    vkGetPhysicalDeviceFormatProperties = reinterpret_cast<PFN_vkGetPhysicalDeviceFormatProperties>(vk.get_instance_proc_addr(vk.instance, "vkGetPhysicalDeviceFormatProperties"));
    if (!vkGetPhysicalDeviceFormatProperties) throw std::runtime_error("Missing frontend Vulkan function: vkGetPhysicalDeviceFormatProperties");
    vkGetPhysicalDeviceProperties = reinterpret_cast<PFN_vkGetPhysicalDeviceProperties>(vk.get_instance_proc_addr(vk.instance, "vkGetPhysicalDeviceProperties"));
    if (!vkGetPhysicalDeviceProperties) throw std::runtime_error("Missing frontend Vulkan function: vkGetPhysicalDeviceProperties");
    vkQueueSubmit = reinterpret_cast<PFN_vkQueueSubmit>(vk.get_device_proc_addr(vk.device, "vkQueueSubmit"));
    if (!vkQueueSubmit) throw std::runtime_error("Missing frontend Vulkan function: vkQueueSubmit");
    vkResetCommandBuffer = reinterpret_cast<PFN_vkResetCommandBuffer>(vk.get_device_proc_addr(vk.device, "vkResetCommandBuffer"));
    if (!vkResetCommandBuffer) throw std::runtime_error("Missing frontend Vulkan function: vkResetCommandBuffer");
    vkResetFences = reinterpret_cast<PFN_vkResetFences>(vk.get_device_proc_addr(vk.device, "vkResetFences"));
    if (!vkResetFences) throw std::runtime_error("Missing frontend Vulkan function: vkResetFences");
    vkUpdateDescriptorSets = reinterpret_cast<PFN_vkUpdateDescriptorSets>(vk.get_device_proc_addr(vk.device, "vkUpdateDescriptorSets"));
    if (!vkUpdateDescriptorSets) throw std::runtime_error("Missing frontend Vulkan function: vkUpdateDescriptorSets");
    vkWaitForFences = reinterpret_cast<PFN_vkWaitForFences>(vk.get_device_proc_addr(vk.device, "vkWaitForFences"));
    if (!vkWaitForFences) throw std::runtime_error("Missing frontend Vulkan function: vkWaitForFences");
}
