#!/usr/bin/env python3
"""Generate embedded first-boot NVRAM templates from validated base .srm files."""

import argparse
import struct
from pathlib import Path

MAGIC = b"SM2SRAM\0"
HEADER_SIZE = 64
BACKUP_SIZE = 16 * 1024
EEPROM_SIZE = 128


def crc16_ccitt(data: bytes) -> int:
    crc = 0
    for byte in data:
        crc ^= byte << 8
        for _ in range(8):
            crc = ((crc << 1) ^ 0x1021) & 0xFFFF if crc & 0x8000 else (crc << 1) & 0xFFFF
    return crc


def payload(path: Path) -> tuple[str, bytes]:
    data = path.read_bytes()
    if len(data) != HEADER_SIZE + BACKUP_SIZE + EEPROM_SIZE or data[:8] != MAGIC:
        raise ValueError(f"invalid save container: {path}")
    version, backup_size, eeprom_size, stored_crc = struct.unpack_from("<4I", data, 8)
    game = data[24:56].split(b"\0", 1)[0].decode("ascii")
    expected = path.stem.removesuffix("-base")
    body = data[HEADER_SIZE:]
    if version != 1 or backup_size != BACKUP_SIZE or eeprom_size != EEPROM_SIZE:
        raise ValueError(f"unsupported save layout: {path}")
    if game != expected or stored_crc != crc16_ccitt(body):
        raise ValueError(f"mismatched game or CRC: {path}")
    return game, body


def encode(data: bytes) -> bytes:
    """PackBits-like blocks: high bit is a run, low seven bits are length minus one."""
    result = bytearray()
    offset = 0
    while offset < len(data):
        end = offset + 1
        while end < len(data) and data[end] == data[offset] and end - offset < 128:
            end += 1
        if end - offset >= 4:
            result.extend((0x80 | (end - offset - 1), data[offset]))
            offset = end
            continue
        start = offset
        while offset < len(data) and offset - start < 128:
            end = offset + 1
            while end < len(data) and data[end] == data[offset] and end - offset < 128:
                end += 1
            if end - offset >= 4:
                break
            offset += min(end - offset, 128 - (offset - start))
        block = data[start:offset]
        result.append(len(block) - 1)
        result.extend(block)
    return bytes(result)


def format_bytes(data: bytes) -> str:
    rows = []
    for offset in range(0, len(data), 16):
        rows.append("    " + ", ".join(f"0x{value:02x}" for value in data[offset:offset + 16]) + ",")
    return "\n".join(rows)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("samples", type=Path,
                        help="sm2-nvram-analysis directory containing <game>/generated/saves")
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    samples = sorted(args.samples.glob("*/generated/saves/*-base.srm"))
    if not samples:
        raise SystemExit("no validated base samples found")
    templates = []
    arrays = []
    for path in samples:
        game, body = payload(path)
        encoded = encode(body)
        symbol = "k" + "".join(part.capitalize() for part in game.replace("-", "_").split("_"))
        arrays.append(f"static constexpr u8 {symbol}[] = {{\n{format_bytes(encoded)}\n}};\n")
        templates.append((game, symbol, crc16_ccitt(body)))

    lines = [
        "// Generated by scripts/generate-initial-nvram-templates.py; do not edit.",
        "// Sources are validated *-base.srm samples from the diagnostic campaign.",
        "",
        *arrays,
        "static constexpr Template kTemplates[] = {",
    ]
    lines.extend(f'    {{"{game}", {symbol}, std::size({symbol}), 0x{crc:04x}}},'
                 for game, symbol, crc in templates)
    lines.extend(("};", ""))
    args.output.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
